project:
  type: website

website:
  title: "Good<br>Enough<br>Computing<br>in Science<br>ğŸ‘âš–ï¸ğŸ§‘â€ğŸ’»ğŸ§ª"
  # navbar: true
    # left:
      # - href: index.qmd
        # text: Home
      # - about.qmd
  page-footer: by Igors Dubanevics | 2025 | MIT License

  sidebar:
    style: "floating"
    # search: true
    contents: 
      - text: "Home"
        href: index.qmd
      # - text: "About"
      #   href: about.qmd
      # -  auto: 0?_*

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    mermaid:
      theme: neutral


