project:
  type: website

website:
  title: "Good Enough Computing in Science ğŸ‘âš–ï¸ğŸ§‘â€ğŸ’»ğŸ§ª"
  # navbar: true
    # left:
      # - href: index.qmd
        # text: Home
      # - about.qmd
  page-footer: by Igors Dubanevics | 2025 | MIT License

  sidebar:
    style: "floating"
    # search: true
    contents: 
      - text: "Home"
        href: index.qmd
      - text: "0. Setting Up"
        href: 00_setting_up.qmd
      - text: "1. Terminal"
        href: 01_terminal.qmd
      - text: "VS Code"
        href: 00_vs_code.qmd
      # - text: "About"
      #   href: about.qmd
      # -  auto: 0?_*

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    mermaid:
      theme: neutral
    callout-appearance: simple


